language: python
dist: xenial
python:
  - 3.6

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pycodestyle

script:
  - cd source/apiVolontaria
  - coverage run --include=apiVolontaria/*,location/*,order/*,volunteer/* --omit=*__init__*,*migrations/*,*tests/* manage.py test .
  - pycodestyle --count --show-source --exclude=migrations,.*,__pycache__,docs,env  .

after_success:
  coveralls
